### ISSUE TITLE
MultiHandleSliderExtender preventing other methods of updating the text of the bound textbox

### ISSUE THREAD

**Issue by R-McN** [DevExpress/AjaxControlToolkit#103]
I have two sliders, one for an X coordinate and the other for a Y coordinate. I also have buttons to nudge the X and Y values in their respective textboxes.

If I use the nudge buttons first, everything is fine - the bound textbox values update and the slider positions update (and ultimately the component within an image is moved to the new coordinates). However, when I use the sliders to update the X and Y values, it works as expected - BUT the nudge buttons can no longer be used to update the X and Y values. The server side code for the nudge buttons seems to be updating the X and Y text values, but the changes get lost somewhere.

The X and Y textboxes are not databound and their values are not changed during post backs. I just seems that as soon as the slider thumb is used, it prevents anything else changing its associated textbox.

Is there some way to temporarily disable a slider while its associated textbox gets updated? Or any other approach that I should be looking at?

The attached screenshot will hopefully help...

Thanks
Richard

![multihandleslideextender](https://cloud.githubusercontent.com/assets/19165091/15219688/a1356440-185c-11e6-861e-fa3a6efd5427.png)

**Comment by AlekseyMartynov** [comment]
@R-McN thanks for the detailed description, however such cases are better to be debugged. Any chance you could attach your project or a part of it?

My best guess is that textbox values are overwritten by other code.

**Comment by R-McN** [comment]
It’s difficult to extract just this bit of code, but I’ve ‘achieved’ similar results in the AjaxControlToolkit sample site application. I’ve attached slightly updated versions of the MultipleHandleSlider example.

Thanks for your help.
Richard

**Comment by MikhailTymchukDX** [comment]
### Client state

This behavior occurs because of the client state used by the extender.

When MultiHandleSlider loads for the first time, the client state is empty, so the extender tries to parse a bound control value and use this value.

After the client state is filled with a value, it prevents an extender's value from being initialized during subsequent page loads. The client-side value of the bound control becomes the only source of the extender's slider value.

### What happened

When you clicked the ImageButton (before touching anything else), you generated a postback, which changed a bound control value, but a client state was empty, so everything was OK.

When you touched the slider handle, it changed a value of the bound control and saved it to the client state. Now, the current value is read from the client state whatever you do with the bound control value on the server.

### What to do

To work around this, set the value in the client-side ImageButton's `OnClientClick` event handler and trigger the `onchange` event of bound textbox to force updating of the client state:
```aspx
<asp:ImageButton ID="ImageButton1" runat="server" OnClientClick="setValue();" />

<script type="text/javascript">
	function setValue() {
		var textbox = document.getElementById("<%= myTextBox.ClientID %>");
		var value = parseInt(textbox.value) + 1;
		textbox.value = value;
		textbox.onchange();            		
	}
</script>
```

**Comment by AlekseyMartynov** [comment]
@MikhailTymchukDX great explanation! But is it a bug which can be fixed on the Toolkit side?

**Comment by MikhailTymchukDX** [comment]
@AlekseyMartynov No. MultiHandleSliderExtender is designed to rely on client-side data and events, so "fixing" this issue will break its behavior.

**Comment by MikhailTymchukDX** [comment]
@R-McN I'm closing this issue.
Feel free to reactivate it if the provided workaround does not help you.
