### ISSUE TITLE
AjaxFileUpload error‏

### ISSUE THREAD

**Issue by luismiguelbp** [DevExpress/AjaxControlToolkit#124]
When I update from v15 to v16.1 the AjaxFileUpload control not working, I try to test by project web page and see the same error

http://ajaxcontroltoolkit.devexpress.com/AjaxFileUpload/AjaxFileUpload.aspx

See the error in attachment. 
![captura_act_error](https://cloud.githubusercontent.com/assets/5835226/15671771/df226e40-272c-11e6-91e5-cdd6b88f2483.JPG)

**Comment by MikhailTymchukDX** [comment]
AjaxFileUpload fails on [Sample site](http://ajaxcontroltoolkit.devexpress.com/) because of the web farm incompatibility issue: #53 
It can also fail because of the Medium trust environment issue: #29

As a workaround for #53, I recommend you switch the Web farm to the sticky mode or downgrade to v15.1 until the next release.
Raising a trust level to `Full` will fix the error in the case of issue #29 . Please see https://github.com/DevExpress/AjaxControlToolkit/issues/43#issuecomment-203437189 for details.

**Comment by MikhailTymchukDX** [comment]
**UPD**: Thank you for pointing out the Sample site issue. We have fixed it.
Let us know if the information we provided before helps you.
