### ISSUE TITLE
Add Preview mode to HtmlEditorExtender

### ISSUE THREAD

**Issue by MikhailTymchukDX** [DevExpress/AjaxControlToolkit#128]
See #97 for details.

**Comment by madhav5589** [comment]
Hello,

I got the CI build in order to get the latest fixes. I got this fix and it worked fine initially. But during testing, I see an issue/bug in the following scenario:
Add the data in htmlEditor in Edit mode. Then click on Preview mode to preview the changes you made. Then go back to Edit mode again, the text/update you made is gone. If you save the form, the htmlEditor value is empty. So basically we lose the change when switching between Edit mode and Preview mode.Can you please confirm ?

Thanks.
