### ISSUE TITLE
How can I configure the asyncfileupload control to support multipe file upload?

### ISSUE THREAD

**Issue by flo-rider** [DevExpress/AjaxControlToolkit#150]
I was using the Ajax controltoolkit version 4.
I installed the latest AJAX Controltoolkit (16.1) from the Visual Studio Nuget packet manager.

But, I don't seem to be able to use the latest version.

It's been installed in `packages\AjaxControlToolkit.16.1.0.0\lib\net40` of  my project. I copied the new `AjaxControlToolkit.dll` file to my application's `bin` folder and replaced the existing dll. I restarted visual studio and also built my application again.

My page code has this:

	<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>

	<cc1:AsyncFileUpload ID="asyncCoverPhoto" CssClass="imageUploaderField" runat="server" ClientIDMode="AutoID" OnClientUploadComplete="uploadCoverphotoComplete" />
	
But I don't see how I can configure the Asyncfileupload control to allow multiple file uploads. I tried adding the attribute `AllowMultiple="true"`, but it doesn't do anything. Also my Visual Studio Intellisense does not show any new attributes (such as the option to allow multiple files to be uploaded)

How can I add a asyncfileupload control that supports multipe files to be uploaded?

**Comment by MikhailTymchukDX** [comment]
The reason you can not see any new attributes is that there are no new attributes in `AsyncFileUpload `since version 4.
You can use the modern upload control, `AjaxFileUpload`, that has this capability by default and controlled by the `MaximumNumberOfFiles` property. Please refer to the [online demo page](http://ajaxcontroltoolkit.devexpress.com/AjaxFileUpload/AjaxFileUpload.aspx) that shows this control feature.

**Comment by flo-rider** [comment]
Hi @MikhailTymchukDX : thanks! I did not know of that control. I've tried to make it available in my Visual Studio toolbox (followed the exact steps outlined in the answer here: http://stackoverflow.com/questions/15258994/how-to-add-ajaxcontroltoolkit-to-toolbox-in-visual-studio-2012). But no controls show up under my new tab (or in the control selection list after I've selected the correct dll for that matter). How can I make use of this new control? Thanks again!

**Comment by MikhailTymchukDX** [comment]
@flo-rider, thank you for reply!

We don't advise to use the NuGet package for Visual Studio toolbar items, because a toolbar is shared across multiple projects, while the NuGet package affects only a particular solution or project. Solution/project removal can lead to a broken reference in a toolbar.

If you want to add toolkit items to a toolbar, the preferred way is to use the [official installer](https://go.devexpress.com/AjaxControlToolkit_Website_Download.aspx), which will register toolbox items for all suitable Visual Studio instances.

However, you can use any control without any issues after installing the NuGet package, so you can copy this code into your page markup:
```aspx
<ajaxToolkit:AjaxFileUpload runat="server" />
```

Make  sure you added this web handler to the `Web.config` file:
```xml
<system.webServer>
  <handlers>
    <add name="AjaxFileUploadHandler" verb="*" path="AjaxFileUploadHandler.axd" type="AjaxControlToolkit.AjaxFileUploadHandler, AjaxControlToolkit"/>
  </handlers>
</system.webServer>
```

**Comment by flo-rider** [comment]
I tried the official installer but get an error that Visual Studio was not found (see attached message). I'm using Visual Studio 2015 Express for Web, does it not work with that (I don't see it in the list in the error message
![vs](https://cloud.githubusercontent.com/assets/7127039/16419894/56806504-3d1d-11e6-9a66-2a0c04f8fc2c.png)
, but want to validate)?

**Comment by MikhailTymchukDX** [comment]
No, Visual Studio Express editions do not support extensions.
You can use [Visual Studio 2015 Community Edition](https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx), which has wider capabilities. This edition is also free.
