### ISSUE TITLE
ValidatorCalloutExtender does not work in Panel with Visible set to false at start

### ISSUE THREAD

**Issue by githieu** [DevExpress/AjaxControlToolkit#21]
Since issue 28018 fix, ValidatorCalloutExtender works again but only if controls are visible on first page load.
If controls are hidden on page load and displayed only after a callback (in my case via a Panel.Visible parameter inside an UpdatePanel), ValidatorCalloutExtender does not work. The validation (in my case RequiredFieldValidator) works because postback is not fired and focus is set to the right textbox (SetFocusOnError="true") but message is not displayed and there is no JavaScript error.

If I set Panel.Visible="true" by default ValidatorCalloutExtender works again but often in my web application, the form to validate is displayed after some user actions and some updatepanel callbacks.

**Comment by githieu** [comment]
I realize that problem is not due to initial visibility of controls but more globally to UpdatePanel refresh. 
If a callback causes an UpdatePanel.Update() all ValidatorCalloutExtenders inside no longer works, regardless of they were visible or not.

**Comment by MikhailTymchukDX** [comment]
Would you please provide a sample project with the described markup so that I can research it?

**Comment by MikhailTymchukDX** [comment]
This issue happens when unobtrusive validation is enabled and jQuery is present.

ValidatorCallout is placed inside the UpdatePanel, so it is recreated after the panel's update.
However, ValidatorCallout attaches to the existing validator before unobtrusive validation code reevaluates page validators using component's `data-val-evaluationfunction` attribute, thus reverting the validation function to the default value.

To fix it, we remove the `data-val-evaluationfunction` attribute from the validator to which ValidatorCallout is attached (see PR #37).
The validator attachment is placed in the [`Sys.Application.load`](https://msdn.microsoft.com/library/bb383829(v=vs.100).aspx) event handler to ensure it is executed regardless of the page update mode.

To temporarily workaround this issue in v16.1.0, call the ValidatorCallout's `_checkPageValidators()` method manually:
```aspx
<ajaxToolkit:ValidatorCalloutExtender
	BehaviorID="ValidatorCalloutBehavior"
	runat="server" />

<script type="text/javascript">
	var firstLoad = true;

	Sys.Application.add_load(function() {

		if(firstLoad)
		{
			firstLoad = false;
			return;
		}

		var behavior = $find("ValidatorCalloutBehavior");
		var element = behavior.get_element();
		element.removeAttribute("data-val-evaluationfunction");
		behavior._checkPageValidators(behavior, element);
	});
</script>
```
