### ISSUE TITLE
font tag not handled correctly by the HTML extender

### ISSUE THREAD

**Issue by gidmeister2** [DevExpress/AjaxControlToolkit#220]
I'm using  AJAX Control Toolkit 16.1.1 that I installed with nu-get in visual Studio Community 2015.
To give some background that is not really needed to show the problem, in my website, I try pasting fragments of Wikipedia pages into the HTMLextender. and then saving them.  
Then I use javascript to manipulate the fragments.
Anyway, I had a fragment that was not working with my javascript, and so I took a few lines of it to see what was wrong, and pasted those few lines into the HTML-extender.
Those lines were:

`<p>
 during the 
<font  color="#0066cc">Black Hawk War</font>
 of 1832.
</p>
<p >
During the 
<font   color="#0066cc">
War of 1812
</font>
, Black Hawk had fought on the side of the 
<font  color="#0066cc">British</font>
 against the U.S.
</p>`
I inserted these in Source-view. 

Then I switched to regular view (of the extender) to see what it looked like.  To my surprise, there were no sections of colored words.
So I switched back to source view and found this.   There are obvious errors in the result:

`<p>&nbsp;during the <font  color="#0066cc">Black Hawk War&nbsp;of 1832.</font ></p><p>During the <font   color="#0066cc">War of 1812, Black Hawk had fought on the side of the <font  color="#0066cc">British&nbsp;against the U.S.</font ></font  ></p>`

It seems that the end-font tag that was after "War of 1812" to moved to the very end, for some strange reason.

So my questions are:
1. why is there no colored font, even with the errors present?
2. why do the errors occur?
3. Is there any work-around at the moment?  Should I take your code and strip out any routines that do "sanitization of html" and just hook it into my project?
4. When are you coming out with your next version?
Thanks.
(The Browser was Microsoft EDGE, and I was running it on my local PC. )

**Comment by MikhailTymchukDX** [comment]
Hi @gidmeister2 ,

2\. This error occurs due to the malformed HTML markup.

1\. Your HTML string contains invalid characters like non-breaking space (ASCII code `0xA0`).
For instance, let's take a look at the `<font color="#0066cc">Black Hawk War</font>` part of the string:

![image](https://cloud.githubusercontent.com/assets/17080984/18392009/d517e6e2-76b8-11e6-881b-580a98a055f3.png)

The string at the top is a normal string.
The string starting at `0x30` position is the part of the string you provided.
Take a note on the 6th character of a second string - it's a non-breaking space (ASCII code `0xA0`), while a normal string has ordinary space (ASCII code `0x20`) at the same position.

HtmlEditorExtender provides unexpected results when it assigns a string with such characters.

3\. To workaround this, check your string before inserting it into the extender and clean it if needed.
Here is a video that demonstrates how correctly a formed string provides expected results:
http://www.screencast.com/t/YajBSTx4usr4

4\. We have no date for the next release at the moment.
If you need the latest version of the toolkit, you can download [a custom build](https://github.com/DevExpress/AjaxControlToolkit/wiki/Updating-the-Project-from-CI-Builds).
