### ISSUE TITLE
What about Visual Studio Express?

### ISSUE THREAD

**Issue by sjcullen** [DevExpress/AjaxControlToolkit#273]
I tried downloading and executing the new Installer, but when it ran, it told me there are no instances of Visual Studio on my machine. I am running VS Express 2012 on a Windows 8 machine.
Is there an alternative installation approach I can use, if the Installer doesn't recognize Express versions?

**Comment by MikhailTymchukDX** [comment]
Hi @sjcullen ,
Yes, AJAX Control Toolkit can not be installed on Visual Studio Express editions as stated in [documentation](https://github.com/DevExpress/AjaxControlToolkit/wiki#visual-studio-support) because it [does not support installation of Visual Studio extensions](https://visualstudiomagazine.com/articles/2014/05/21/no-extensions-for-visual-studio-express.aspx).

You have 2 options to overcome this:
1. Install the [`AjaxControlToolkit` NuGet package](https://www.nuget.org/packages/AjaxControlToolkit/) to a project. You can install the [`AjaxControlToolkit.StaticResources`](https://www.nuget.org/packages/AjaxControlToolkit.StaticResources/) and [`AjaxControlToolkit.HtmlEditor.Sanitizer`](https://www.nuget.org/packages/AjaxControlToolkit.HtmlEditor.Sanitizer/) packages if needed.
2. Upgrade to the [Community edition of the Visual Studio](https://www.visualstudio.com/vs/community/). It is free and allows installation of Visual Studio extensions.
