### ISSUE TITLE
Correctly set handler path in IIS for application and multiple uploads

### ISSUE THREAD

**Issue by gdpollock** [DevExpress/AjaxControlToolkit#294]
This is more of a question about configuration than an issue.  I am using version 16.1.1.0.  I am running a site in IIS 8.  I'm running on default site, application name "hebpslb", so you would access my site as: http://myserver/hebpslb, and the page in question is "http://myserver/hebpslb/Claims/ProcessMedical.aspx"

I managed to get the handlers working both client on web, but I'm having to create multiple handlers for each groups of pages.  I would like information on how to correctly set up handler paths for multiple uploadhandlers.

Here is how I get the control working on the page:
<cc1:AjaxFileUpload ID="fuClaimsFile" runat="server" ThrobberID="myThrobber" MaximumNumberOfFiles="10" AllowedFileTypes="" OnUploadComplete="fuClaimsFile_UploadComplete" UseAbsoluteHandlerPath="false" />

And here is the web.config setting:
```
<system.webServer>
    <handlers>
      <add name="AjaxFileUploadHandler" verb="*" path="hebpslb/Claims/AjaxFileUploadHandler.axd" type="AjaxControlToolkit.AjaxFileUploadHandler, AjaxControlToolkit" />
    </handlers>
```
Everything works fine this way, but if I create new pages not in folder "Claims" I have to create a new handler.  But because I have my site as an application in the default site, I can't use the root.  What I'd like is for my handler path to be "hebpslb/AjaxFileUploadHandler.axd" so I only need one handler for the entire application.  How can I make that happen?

**Comment by MikhailTymchukDX** [comment]
It's not possible to set up multiple AjaxFileUpload handlers in v16.1.1 without writing custom client code that replaces the path to a needed non-root path.
However, I would like to propose another solution.

We added a new property, `UploadHandlerPath`, after the v16.1.1 release so that you can set it to "`http://myserver/hebpslb/AjaxFileUploadHandler.axd`" regardless of the AjaxFileUpload location.

There are 2 ways of getting the code that contains this property:
1.  Follow the [Updating the Project from CI Builds](https://github.com/DevExpress/AjaxControlToolkit/wiki/Updating-the-Project-from-CI-Builds) article.
2. Download our [preview installer with VS 2017 RC support](http://cdn.devexpress.com/Release/ACT/17.1/20170130/AjaxControlToolkit.Installer.17.0-preview.exe?customer=trial&Expires=1809032400&Signature=Mlyed6Mlvmpy490toLYqMGbweiwX7n3vmU3pu6j3Ze9NjxK%7EpBhxGxRMo5VrB-RGsKkmOiU2hg7ELssditHaxRnRN3MxR-5OTQynNZNPnjlNXunCT-plJrHw9urNY6loJQ3t0vnz1EXFzky64sIU6PzMfybzcZfP9d7KtBEsfU0_&Key-Pair-Id=APKAJXDNBD2DCSFOCFMQ).

Feel free to comment if you need additional help.

**Comment by gdpollock** [comment]
So just to clarify, if I modify the AjaxFileUpload control, I can manually set the location it will search for the handler, and then have web.config set that path?

If so, does the UploadHandlerPath have to be a literal path, or can it be relative?  Can I say UploadHandlerPath="~/AjaxFileUploadHandler.axd" and it will know to search for "myserver/hebpslb/AjaxFileUploadHandler.axd"?

**Comment by MikhailTymchukDX** [comment]
This property is transferred as is to a client. So, you can not use a tilde symbol there, but you can put a relative path starting with a slash.

**Comment by gdpollock** [comment]
I appreciate your help on this.  I will attempt to upgrade the toolkit and use the UploadHandlerPath.
