### ISSUE TITLE
HtmlEditor does not show toolbar images when EnablePartialRendering=true

### ISSUE THREAD

**Issue by andrewchilcott** [DevExpress/AjaxControlToolkit#324]
### The installation method
- [ ] Installer

### Minimal steps to reproduce the bug
Add an HtmlEditorExtender to a TextBox in the EditItemTemplate of a ListView inside an UpdatePanel inside an ascx UserControl inside an aspx page using site.Master.

Within the site.Master file an asp:ScriptManager is loaded

### Actual result
When ScriptManager EnablePartialRendering = true then the control appears without any images on the buttons.
![htmleditorlostassets](https://cloud.githubusercontent.com/assets/6161848/24921458/d371819a-1ee2-11e7-868f-d8d561fc2b1d.PNG)

### Expected result
When ScriptManager EnablePartialRendering = false then the control appears with images on the buttons.
![htmleditorwithassets](https://cloud.githubusercontent.com/assets/6161848/24921472/dfd6f906-1ee2-11e7-9352-da5691cac9ba.PNG)

### A site deployment method
- [ ] VS development web-server,

Obviously, turning partial rendering off is not what I want to do. I want the control to work with partial rendering of the page.

I understand from lots of old postings from a Google search that this was a known problem over several years. I could not find a resolution. Was this one of the bugs that was addressed when DevExpress took over the code maintenance? If so, what is the solution?

Andrew Chilcott

**Comment by MikhailTymchukDX** [comment]
Hi @andrewchilcott,
 
I would like to thank you for bringing such an interesting issue to our attention. It was not addressed earlier, because we didn't test such CSS-rich control inside an UpdatePanel.
 
This bug comes from the way toolkit registers CSS links for a control.
 
When there is no UpdatePanel or `EnablePartialRendering = false` the links to CSS resources are injected into the code via server code: https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit/ToolkitResourceManager.cs#L203-L208
 
However, when an async postback arrives from an UpdatePanel, these links are rendered inside the UpdatePanel's DOM using the client script: https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit/ToolkitResourceManager.cs#L221-L235
 
We cannot suggest any workaround for this issue, but the fix is underway.
