### ISSUE TITLE
SliderExtender does not create successfully when dynamically added from an AJAX postback

### ISSUE THREAD

**Issue by MicrosoftTE** [DevExpress/AjaxControlToolkit#329]
Version of toolkit : 17.1.0.0
Component : SliderExtender
Issue : SliderExtender can not be dynamically added to a page during an AJAX postback, if it is it will fail to change the rendering of the textbox to be a slider control.

NOTE: Example project attached with issue and workaround.
[SliderIssueRepro.zip](https://github.com/DevExpress/AjaxControlToolkit/files/980516/SliderIssueRepro.zip)

### Minimal steps to reproduce the bug

1. Extract the attached reproduction project (SliderIssueRepro.zip) and rebuild to get nuget packages.
2. Examine code and Run
3. Press the repro button to create a slider control dynamically on ajax postback.

### Work around

1. Extract the attached reproduction project (SliderIssueRepro.zip) and rebuild to get nuget packages.
2. Examine code and uncomment the SliderWorkaround() call in the Page_Load event of default.aspx.cs
3. Press the 'Make it work with a workaround' button.

Attached is a project demonstrating the issue.

### Actual result

ExtenderSlider does not correctly create (still has a textbox).

### Expected result

ExtendedSlider should correctly create (has the replaced slider)

**Comment by Mehul** [comment]
@MicrosoftTE Steve, thanks and happy to have an original ACT dev help us with this library. Our devs will look into this soon.

**Comment by MikhailTymchukDX** [comment]
Hi @MicrosoftTE,
 
Thank you for such a cool example!
 
The reason for this is obvious - when an extender is created dynamically inside an UpdatePanel, there are no scripts and images loaded for this extender beforehand. This can be easily checked with the page source code.
 
If we had a simple control, we could call the `RegisterStartupScript()` method as described here: http://stackoverflow.com/a/1953122
 
However, things are a bit more complex when working with controls based on [Microsoft AJAX](https://msdn.microsoft.com/en-us/library/bb398874.aspx).
 
Resource links for extenders are rendered with [ScriptManager](https://msdn.microsoft.com/en-us/library/system.web.ui.scriptmanager(v=vs.110).aspx), which gets resource entries from all extenders on the page and normalizes them by removing duplicates.
If we blindly force rendering of all scripts for SliderExtender when it's created dynamically, this may lead to duplicates and runtime errors.
Also, the logic of rendering image links is executed internally and is not available from user code.
 
As such, we treat this behavior as by design.
 
If you have any ideas how to instantiate this extender in an asynchronous postback properly, I would love to hear them.
Feel free to share your ideas because this can make significant impact to AJAX Control Toolkit usability as a whole.

**Comment by AlekseyMartynov** [comment]
@MikhailTymchukDX 
Instead of "by desing", I'd say it's a known limitation of MS Ajax and UpdatePanel.

Alternative workaround is to always create the slider, but invisible, and set `Visible` to `true` on the button click.

Here are suggested edits.

In the markup, move the button out of `demoPanel`:

```xml
<asp:Panel id="demoPanel" runat="server"></asp:Panel>
<asp:Button id="repoIssue" runat="server" OnClick="repoIssue_Click" Text="Reproduce Issue"/>
```

In the code-behind:

```c#
protected override void OnInit(EventArgs e) {
    base.OnInit(e);
    CreateSliderControl(demoPanel);
    demoPanel.Visible = false;
}

protected void repoIssue_Click(object sender, EventArgs e) {
    //CreateSliderControl((sender as Button).Parent);
    demoPanel.Visible = true;
}
```

Also, in order to preserve state on subsequent postbacks, fixed IDs are required, not random GUIDs.
