### ISSUE TITLE
Current project builds fails with vs2013 as of May 21, 2017

### ISSUE THREAD

**Issue by kallal** [DevExpress/AjaxControlToolkit#334]
### The AJAX Control Toolkit \<VERSION\>
current master as of may 21, 2017

### The installation method
- [ ] Installer
- [ ] NuGet package
- [ ] A custom build from the source code

no install - only attempted build in vs2013

### Minimal steps to reproduce the bug
download as zip, or clone via github
attempt build with vs2013
Build fails
see attached screen shot.
### Browser(s) used

![aj1](https://cloud.githubusercontent.com/assets/15162420/26288564/37a0d8ee-3e52-11e7-8e66-2e75f0670774.png)
### A site deployment method
- [ ] VS development web-server,
- [ ] IIS

**Comment by MikhailTymchukDX** [comment]
Hi @kallal 
These errors occur because of C# language features that are used in our utility projects.

You don't need these projects to compile the AJAX Control Toolkit, so you can exclude them from building:
![image](https://cloud.githubusercontent.com/assets/17080984/26299284/fca0d302-3ee2-11e7-9af0-8678bb255fe2.png)
![image](https://cloud.githubusercontent.com/assets/17080984/26299290/ffd57b18-3ee2-11e7-8382-2d40a7e1b4ce.png)

However, if you want to build the entire solution, you can use VS 2015 or later.

**Comment by kallal** [comment]
Thank you kindly - that indeed works great and fixes this issue. For most just grabbing nuget working library is fine and no "build" of the source is required. However for anyone wanting to modify this project or have their own "base" build to control updates then the build failure will scare away potential contributitors. So for those in regards to bug fixes or useful tweaks the advice here works well and allows a buld with 2013. .

In my case I want to add a "Time Remain" in the ajaxFileUpload.  If I can make the setting 100% backwards compatible with existing projects then I will propose and submit this change to the build.  Regardless, this works (the post build copy command still fails - but I think that's ok)
