### ISSUE TITLE
Where is AjaxFileUploadHandler.axd"

### ISSUE THREAD

**Issue by kevinkey619b** [DevExpress/AjaxControlToolkit#354]
Can someone tell me where the heck I find AjaxFileUploadHandler.axd"? Is this why I get a generic (error) every single time I attempt to upload a file?

Does this toolkit support the 4.5 framework?

Can someone please provide the proper instructions for setting up AJAX File Upload?

**Comment by MikhailTymchukDX** [comment]
Hi @kevinkey619b 
AjaxFileUploadHandler.axd is a runtime generated HTTP Handler: https://stackoverflow.com/a/5879852

Yes, the toolkit supports the 4.5 framework.

To set up an AjaxFileUpload, add AjaxFileUploadHandler to the `system.webServer/handlers` section of Web.config:
```xml
<system.webServer>
  <handlers>
    <add name="AjaxFileUploadHandler" verb="*" path="AjaxFileUploadHandler.axd" type="AjaxControlToolkit.AjaxFileUploadHandler, AjaxControlToolkit"/>
  </handlers>
</system.webServer>
```

There is a whiltelist of allowed extensions since v17.1.1: https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit/AjaxFileUpload/AjaxFileUploadHelper.cs#L14-L44

If you need to upload files with other extensions, add these extensions to a new optional setting in Web.config:
```xml
<ajaxControlToolkit additionalUploadFileExtensions="obj,pdb" />
```

**Comment by kevinkey619b** [comment]
I got it working now. Thanks.
