### ISSUE TITLE
AjaxFileUpload Control : file gets corrupted if filename had a chinese character

### ISSUE THREAD

**Issue by tokne** [DevExpress/AjaxControlToolkit#408]
uploading was successful but when i tried to download the excel file the file was corrupted.

![upload1](https://user-images.githubusercontent.com/6957207/35575480-5d024e66-05d4-11e8-8dc8-e46d07ae3a8b.JPG)

![upload2](https://user-images.githubusercontent.com/6957207/35575644-d6d6d842-05d4-11e8-84fb-d332e8de0235.JPG)

**Comment by MikhailTymchukDX** [comment]
Hi @tokne,
I tried to load a file with Chinese characters in its name using the latest AJAX Control Toolkit 18.1 and had no errors.
Would you please specify the version of the toolkit you are using and provide a sample file name to test this control?

**Comment by tokne** [comment]
Hi,

Create an excel file and save is as 17XKL043 发票.xlsx. After uploading try to open the file where it was saved.  

Version:
![upload3](https://user-images.githubusercontent.com/6957207/35628342-84d93750-0693-11e8-9658-640b68dbc711.JPG)

**Comment by MikhailTymchukDX** [comment]
@tokne 
This bug was fixed in the AJAX Control Toolkit v15.1.3 (see [release notes](https://community.devexpress.com/blogs/aspnet/archive/2015/08/18/asp-net-ajax-control-toolkit-v15-1-3-maintenance-update-available.aspx) item 27655).

You cannot upload files with Unicode characters in the filename, so either rename them before uploading or update the toolkit.
[Here is a guide](https://github.com/DevExpress/AjaxControlToolkit/wiki/Upgrading-from-v7.x-and-below) for upgrading from pre-v15.1 versions.
