### ISSUE TITLE
AsyncFileUpload does not fire the UploadedComplete event when the AsyncFileUpload control is not visible during the initial load of a page

### ISSUE THREAD

**Issue by Bartolomeus-649** [DevExpress/AjaxControlToolkit#422]
AsyncFileUpload does not fire the UploadedComplete event when the AsyncFileUpload control is not visible during the initial load of a page, and using UpdatePanels for all remaining updates to the page.

It seems like the control registers/references resources during the initial request, and when the control is invisible these resources are not registers/references,  later on when the control becomes visible these resources are not available which prevent the UploadedComplete from working as it should.

More info
[https://forums.asp.net/t/1489399.aspx](https://forums.asp.net/t/1489399.aspx)
[https://forums.asp.net/t/1479689.aspx?PageIndex=2](https://forums.asp.net/t/1479689.aspx?PageIndex=2)

Toolkit version: 16.1.1
VS development web-server
Chrome/Edge/IE/FireFox
Installed via Nuget

**Comment by MikhailTymchukDX** [comment]
Hi @Bartolomeus-649 
Yes, you are right - [script references are not rendered to a page if a control is not visible](https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit/ExtenderBase/ScriptControlBase.cs#L157).

[In the second link](https://forums.asp.net/t/1479689.aspx?PageIndex=2) you provided, I see workarounds provided by **obout_teo**.
Did you try to apply them?

**Comment by Bartolomeus-649** [comment]
it's a bug to assume that you can render ScriptReferences on any postback request.
Only during the initial request to a page  can you be sure you have the ability to reister/render any resources being used by a control.
Postback-requests can be partial rendering if the page uses UpdatePanel, and during a partial render you can not modify anything outside the UpdatePanel.

So weather the control is visible or not, all resources/references must be registered and rendered during the initial request.

_A workaround is possible by adding a "dummy" AsyncFileUpload  to the page, outside any initially hidden controls, with its style set to "visibility: hidden"._

**Comment by Bartolomeus-649** [comment]
...Also this prevent the use of AsyncFileUpload inside a MultiView (as long as it is not on the initial view shown)

**Comment by MikhailTymchukDX** [comment]
Hi @Bartolomeus-649 
I digged deeper into the problem and found that my initial comment was not related to your problem.
Sorry for misleading you.

The reason behind the missing event raising was the incorrect form encoding type, as **obout_teo** already noted:
```
<form runat="server" enctype="multipart/form-data">
   ...
</form>
```
Once set it to `multipart/form-data` in page markup, the `UploadedComplete` event was raised successfully.
This is the sample project that I created based on your description: [AsyncFileUploadUpdatePanel.zip](https://github.com/DevExpress/AjaxControlToolkit/files/1810669/AsyncFileUploadUpdatePanel.zip)

If it does not reflect your case, please update it and attach a modified version to this thread.

As for using AsyncFileUpload inside a MultiView, would you please provide a sample project that illustrates the issue so that we can research this case?

**Comment by MikhailTymchukDX** [comment]
Since we still haven't received the requested information, I'm closing this issue.
Once you have any additional info regarding the error, please notify us by adding a comment.
