### ISSUE TITLE
AjaxcontrolToolkit does not work after deploy to the Windows Server

### ISSUE THREAD

**Issue by cheahengsoon** [DevExpress/AjaxControlToolkit#530]
### The installation method
- [X] Installer
- [X] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
 When I debug my application which are using Ajax Control Toolkit ComboBox, its work in my machine. After deploy to the Windows Server 2012, its did not work well as I expected.
Its that Windows Server 2012, missing any installation?

### Actual result
<img width="661" alt="localmachinework" src="https://user-images.githubusercontent.com/2833325/79703545-10d60200-82df-11ea-9eaf-67b87f3fb57f.png">

### Expected result
<img width="567" alt="ServerError" src="https://user-images.githubusercontent.com/2833325/79703559-29deb300-82df-11ea-8648-1ab64fe76a19.png">

### Browser(s) used
Microsoft Edge and Chrome

### A site deployment method
- [X] VS development web-server,
- [X] IIS

https://stackoverflow.com/questions/61301497/ajaxcontroltoolkit-does-not-work-after-deploy-to-the-windows-server

**Comment by AlekseyMartynov** [comment]
Since the [mentioned SO thread](https://stackoverflow.com/q/61301497) has comments and answers, I'm closing this ticket.

Possibly related:
- [Could not load file or assembly on Windows 2012 r2](https://github.com/DevExpress/AjaxControlToolkit/issues/51)
- [AjaxFileUpload won't upload once site is published to IIS7](https://github.com/DevExpress/AjaxControlToolkit/issues/424)
