### ISSUE TITLE
Empty watermark text throws exception

### ISSUE THREAD

**Issue by donvnielsen** [DevExpress/AjaxControlToolkit#536]
### The AJAX Control Toolkit \<VERSION\>
AjaxControlToolkit.19.1.0
### The installation method
- [ ] Installer
- [x] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
Implement date control and :
            // watermark (placeholder)
            _wmExtender.TargetControlID = _textBox.ID;
            ClearWatermark();
            Controls.Add(_wmExtender);

The set the value to null or string.Empty

_wmExtender.WatermarkText = "";

### Actual result
Attempt to display the page throws exception

### Expected result
An empty text box

### Browser(s) used
Chrome

### A site deployment method
- [x] VS development web-server,
- [ ] IIS

**Comment by donvnielsen** [comment]
I can share this control implementation:

[CalendarTextBox.txt](https://github.com/DevExpress/AjaxControlToolkit/files/4599874/CalendarTextBox.txt)

**Comment by AlekseyMartynov** [comment]
This exception is expected because the `WatermarkText` property is required:

https://github.com/DevExpress/AjaxControlToolkit/blob/4a8f333f538909bf9030671e3f5aa80dc4707c50/AjaxControlToolkit/TextBoxWatermark/TextBoxWatermarkExtender.cs#L49-L55

You can conditionally create and initialize the `TextBoxWatermarkExtender` in `CreateChildControls`. Don't create it if `Watermark` is empty.
