### ISSUE TITLE
Is version 3.0.30512.0 still supported?

### ISSUE THREAD

**Issue by ChrisSfanos** [DevExpress/AjaxControlToolkit#545]
### The AJAX Control Toolkit 3.0.30512.0

Message from the NuGet community:  Is version 3.0.30512.0 still supported?

**Comment by Mehul** [comment]
@ChrisSfanos I recommend all users of past ASP.NET AJAX Control Toolkit **upgrade** to the [latest version](https://github.com/DevExpress/AjaxControlToolkit/releases) because many security issues and bugs have been resolved since the early versions:

[ASP.NET AJAX Control Toolkit - Release Blog posts](https://community.devexpress.com/tags/AjaxControlToolKit/default.aspx)
