### ISSUE TITLE
Object doesn't support property or method 'resetUI'

### ISSUE THREAD

**Issue by ajmorgs** [DevExpress/AjaxControlToolkit#65]
I am using the ajaxFileUpload control in a web app running under IIS7 on Windows 2012 server. After choosing the file to upload, I click 'Upload' and the following error occurs:    Object doesn't support property or method 'resetUI' and the debugger stops in the function below.

raise_uploadError: function(e) {
        var eh = this.get_events().getHandler("uploadError");
        if(eh) {
            eh(this, e);
        }

        this._processor.resetUI();

        this._canceled = false;
        this._isUploading = false;
        this._isUploaded = true;
        this.enableControls(true);
    },

**Comment by MikhailTymchukDX** [comment]
Would you please specify browser version that you use when this error occurs?

**Comment by ajmorgs** [comment]
I'm using IE11. The server has .Net 4.5.1 installed.

**Comment by MikhailTymchukDX** [comment]
This happens when a browser does not support HTML 5 and an error occurs during uploading.

IE 11 does support HTML 5, so please try the following:

1. Check your document mode in Developer Tools (F12) - it seems the page is reset to an older document mode that does not support HTML 5.
You can change page document mode to `Edge (Default)` from the dropdown list to make sure a page works properly in HTML 5 mode.
This can happen when you set a site to be rendered in [Compatibility Mode](http://windows.microsoft.com/en-us/internet-explorer/use-compatibility-view#ie=ie-11).

2. Make sure this tag is added to the `<head>` section of a page:

    ```html
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    ```
3. If you still encounter the error every time you try to upload a file, this can mean your site is running in Medium trust environment. In this case, please apply this workaround: https://github.com/DevExpress/AjaxControlToolkit/issues/43#issuecomment-203437189

4. If you run a site on a web farm, please use the codebase starting with this commit: https://github.com/DevExpress/AjaxControlToolkit/commit/051d675233b61601cbcba899284f72ac3d0cde5c

**Comment by ajmorgs** [comment]
Changing the doctype to HTML5 and adding the meta tag worked. Thanks for your help!
