### ISSUE TITLE
CSS appears to be incorrect for Tabs in Chrome/IE 11

### ISSUE THREAD

**Issue by uberDoward** [DevExpress/AjaxControlToolkit#79]
v16.1.0 of AjaxControlToolkit.  Element style for .ajax__tab_body renders as display:block, and is causing inside content to be rendered incorrectly.

Setting to display:inline-block appears to help, in my case I also need a margin-top:8px to render correctly, but I'm thinking that's due to my padding of 8px on the interior asp:panel

Just FYI :)

**Comment by uberDoward** [comment]
Line 460 of AjaxControlToolkit.TabContainer

Changed:
writer.AddStyleAttribute(HtmlTextWriterStyle.Display, "block");

To:
writer.AddStyleAttribute(HtmlTextWriterStyle.Display, "inline-block");

Rebuilt, used new assembly, and working for me now :)

**Comment by MikhailTymchukDX** [comment]
Would you please provide a sample project that illustrates this issue?

**Comment by uberDoward** [comment]
It may take me some time - I'm pretty busy, but if I get a chance to, I'll do so :)

**Comment by MikhailTymchukDX** [comment]
@uberDoward 
We cannot change this attribute value because it will likely cause breaking changes in applications of existing users. So, I'm closing this issue for now.

Feel free to reopen it when you are ready to share a sample project, so that we can evaluate if we need to make this change to the source code.
